name: Token Transfer

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run token transfer
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          RECEIVER_ADDRESS: ${{ secrets.RECEIVER_ADDRESS }}
        run: node index.js
